### ISSUE TITLE
[Question] replace ESC from edii to ediv?

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#19]
Hi

Is it possible to change the command from Esc to something else like <Esc-Left>? The reason is that this way I could work with edii ediin with many windows, without needing to switch to guii. The only thing preventing me from doing this right now is that the Esc key is needed in many applications, but every time i click it it switches back to edin, which I don't want to.

Thanks!
Gil

**Comment by pit-ray** [comment]
Thanks again!

I don't know whether I understand, but do you want to transition to **Edi Normal** with another key instead of Esc-based switching like Vim.

If then, all you need is changing bindings with GUI or rewriting `~/.wim-vind/bindings.json` directly.
For example, to transition to **Edi Normal** with `Left Ctrl -> Left Shift`.

**Before**
``` json
{
        "name": "change_to_edi_normal",
        "guin": ["I", "gI"],
        "guii": [],
        "guiv": [],
        "edin": ["<Esc>"],   <====
        "edii": ["<edin>"],
        "ediv": ["<edin>"],
        "edivl": ["<edin>"],
        "cmd": [],
        "mycwn": [],
        "mycwi": [],
        "en": "Normal Mode (Vim Emulation: <Esc>)",
        "ja": "ノーマルモード (Vim エミュレーション: <Esc>)"
    },
```
**After**
```json
  "edin": ["<lc><ls>"], 
```

**Comment by gilbh** [comment]
Thanks for the reply!

I entered this is the json:
```
        "edin": ["<Esc-Left>","<Esc-Right>","<Esc-Up>","<Esc-Down>","<F9>"],
```

-- but still, when in am in `edii` and I clicked Esc, it switches to `edin`. This causes a problem. How to disable Esc?

**Comment by pit-ray** [comment]
If you directly rewrote, you should reload the json, so please restart win-vind. Oh yeah, I must implement the command like `:source`.   

The bindings are the same as `edin`, so will probably occur undefined choice of functions. In this case, change or remove `edi*` bindings in `change_to_normal` (transition to `guin`).  

For example,
**Before**
``` json
    {
        "name": "change_to_normal",
        "guin": ["<Esc-Left>","<Esc-Right>","<Esc-Up>","<Esc-Down>","<F9>","<Capslock>"],
        "guii": ["<guin>"],
        "guiv": ["<guin>"],
        "edin": ["<guin>"],  <====
        "edii": ["<guin>"],  <====
        "ediv": ["<guin>"],  <====
        "edivl": ["<guin>"], <====
        "cmd": [],
        "mycwn": ["<guin>"],
        "mycwi": [],
        "en": "GUI Normal Mode",
        "ja": "GUI ノーマルモード"
    },
```

**After**
```json
        "edin": ["<F8>"],
        "edii": ["<edin>"],  <==== Same as edin
        "ediv": ["<edin>"],  <==== Same as edin
        "edivl": ["<edin>"], <==== Same as edin
```
![mode_overview_fa](https://user-images.githubusercontent.com/42631247/116502668-1d783780-a8ef-11eb-82ef-6e392c0f0b87.jpg)

**Comment by gilbh** [comment]
Thanks. I tried it and it does not work:
```
    {
        "name": "change_to_normal",
        "guin": ["<Esc-Right>"],
        "guii": ["<guin>"],
        "guiv": ["<guin>"],
        "edin": ["<Esc-Left>"],
        "edii": ["<edin>"],
        "ediv": ["<edin>"],
        "edivl": ["<edin>"],
        "cmd": [],
        "mycwn": ["<guin>"],
        "mycwi": [],
        "en": "GUI Normal Mode",
        "ja": "GUI ノーマルモード"
    },
```
Still, when  I am in `edii` and click Esc, I get `edin` (which  I am trying to disable, Esc should do nothing in win-vind, and be caught at the window itself.

On your comment about `:source `: I see you have an Apply button, why not reload binding in it?

I want to praise your work, I think win-vind is brilliant and I work with it daily. I was waiting for years for someone to pick this challenge up and your implementation works great.

Best!

**Comment by pit-ray** [comment]
By the way, is your version of win-vind **v3.2.3**? **v3.2.2** has some issues in GUI.

I made sample bindings.json, so please try to replace it in `~/.win-vind/bindings.json` **after backup your settings**. The sample bindings state in the attached figure. Then, win-vind must be restarted.

https://gist.github.com/pit-ray/9d7b435c30f4e54d3fb03b34f3b3267b

![fix_mode](https://user-images.githubusercontent.com/42631247/116819518-55130800-abab-11eb-8c2a-4c5f5e0fa6c5.jpg)


If the replacing test does not work, try to disable `Suppress for Vim` or `Dedicate to One Window` options.


About `:sources`. 
The `Apply` button and `OK` reload all settings, even if use the current win-vind. However, if we change settings by rewriting `~/.win-vind/bindings.json`

 without GUI, we must open GUI even though don't needs to use it. Thus, some unti GUI users will misunderstand this behavior.

Your contribution in Issues are very helpful to the development of win-vind. Thanks.

I hope it works.

**Comment by gilbh** [comment]
My version is 3.2.3.

I am trying now your bindings at it appears to work! There is a larger question here to think about. Let me know if the following description is correct: you created GUI Normal to manage windows, and then GUI Insert for regular Windows use. I, on the other hand, am trying to work in EDI Insert for regular Windows use, and switch to EDI Normal to have Vim textual operations (only).

Now, with disabling Esc from EDI Insert to EDI Normal, EDI Insert works great for me as the *default* general Windows operations... If I want some Vim functionality, I turn on EDI Normal (using  Esc-left binding). 

I am laying this out here so we can reflect on the possible usages of your app.... maybe both ways are fine??

On `:source` -- I think I understand your worry, but it is really a marginal case -- perhaps just open a message in that special case? I think it is still worth to have `Apply` run a full reloading, as `:source`.

In general: I know this is in your to do list, but `e` and `c` functions would add a lot to the user experience, at least mine. But take your time if you need it, `win-vind` is great as it is!

BTW -- would you consider renaming the project? Not a big deal at all, but I thought it would be cute to call it i with some easy clear name, like "vindows".... just a thought....

Thanks,
Gil

**Comment by pit-ray** [comment]
Sorry for my long reply.

- Mode Model
  The mode model in default bindings is based on GUI Normal due to its development history. However, your proposed model is probably like the next figure?  
  <img src="https://user-images.githubusercontent.com/42631247/117316529-a4b34580-aec3-11eb-8e2f-fd841b7bea91.png" width=400 />  
  
  In this model, Edi Normal cannot adapt <Esc> as default bindings, but the simple structure and the ease to understand are appealing. I will consider it for 4.x version.

- `:source` and Apply
  I'm sorry. I wrote it in a way that could be misunderstood. `Apply` and `OK` buttons in the current win-vind v3.2.3 **RUN** a full reload. I'm considering `:source` as a third button that does not depend on the GUI.

- `e` and `c`
  `c` is already implemented.

- The project name
  The original name of this project was **vind**, which means **vi/Vim** + **bind**, **win-vind** is its Windows version. If it were to support macOS or Linux, I would create a new repository call vind, but perhaps Linux would not necessary because it has the window management system.  About **vindows**, Google shows it as a Windows typo, so it would not good as search performance.   
  <img src="https://user-images.githubusercontent.com/42631247/117316764-da582e80-aec3-11eb-8d9f-395464bd6ab7.jpg" width=300>

- My consideration for 4.x.
  I introduced the GUI to reduce the learning cost, but it's maybe not easy to understand. Now, I'm considering Run-Commands style like `.vimrc`. For example, following.

  **.vindrc**
  ```vim
  set keybrdtype=US
  set initmode=edii
  set suppress_for_vim
  set vscrollspeed=10
  
  ediimap <esc-left> <esc>
  " or
  ediimap <esc-left> change_to_edi_normal
  ```
  
  Opinions are welcome.

**Comment by gilbh** [comment]
Thanks for this thoughtful post. 

As for diagram: yes, I think this is getting closer to what my daily experience of using Vind is. It solves additional problems, such as having the default activation in insert mode, which will make easier for newbies. Please consider.

BTW, how can I swap bindings between `EDI Normal` and `GUI Normal`? I am asking since `<Esc-right>` works better for me with `EDI Normal`, which I am using frequently:
```
    {
        "name": "change_to_normal",
        "guin": ["<Esc-Right>"],
        "guii": ["<guin>"],
        "guiv": ["<guin>"],
        "edin": ["<guin>"],
        "edii": ["<guin>"],
        "ediv": ["<guin>"],
        "edivl": ["<guin>"],
        "cmd": [],
        "mycwn": ["<guin>"],
        "mycwi": [],
        "en": "GUI Normal Mode",
        "ja": "GUI ノーマルモード"
    },
```

The project name: yes, I see the problem with `Vindows`, but perhaps something without the `-` dash? Maybe `vindwin`?

GUI setup: I actually think it works well, not sure introducing a new set of vim-like commands will not be too complicated to master....

That's my feedback... keep up to good work!

Gil

**Comment by pit-ray** [comment]
Sorry for the late reply.

If you want a way to transition between GUI Normal and Edi Normal, you can exchange them. Please change `<Esc-Left>` to `<Esc-Right>` in `change_to_edi_normal`, and `<Esc-Right>` to `<Esc-Left>` in `change_to_normal`.

**Before**
```json
        "name": "change_to_normal",
        "guin": ["<Esc-Right>"],
```
```json
        "name": "change_to_edi_normal",
        "guin": ["I","gI"],
        "guii": [],
        "guiv": [],
        "edin": ["<Esc-Left>"],
```

**After**
```json
        "name": "change_to_normal",
        "guin": ["<Esc-Left>"],
```
```json
        "name": "change_to_edi_normal",
        "guin": ["I","gI"],
        "guii": [],
        "guiv": [],
        "edin": ["<Esc-Right>"],
```

I implemented the rc-style settings with almost the same commands as Vim, and I thought better than GUI. But I will also continue to support the GUI.

Thanks.

**Comment by gilbh** [comment]
Thanks. 

I tried pasting the "After" section but after saving, the first two lines are deleted from the json file. It seems that it cannot take two "name" entries?

Gil

**Comment by gilbh** [comment]
Sorry,

Still having issues with bindings ...  I am actually quite confused now as for how to switch from `edii` back to `edin'.... I re-pasted an earlier version of the json:
```
    {
        "name": "change_to_normal",
        "guin": ["<Esc-Left>"],
        "guii": ["<guin>"],
        "guiv": ["<guin>"],
        "edin": ["<guin>"],
        "edii": ["<edii>"],
        "ediv": ["<edin>"],
        "edivl": ["<edin>"],
        "cmd": [],
        "mycwn": ["<guin>"],
        "mycwi": [],
        "en": "GUI Normal Mode",
        "ja": "GUI ノーマルモード"
    },
```

But when I try clicking `<Esc-Right>` nothing happens (except cursor move)...

Then I tried `Return to Default` and adding to it:
```
 "edin": ["<Esc-Right>"],
```

However, it still does not work. Actually, only when I click `I` from `edii` I get to `edin`. But that is unreasonable, because I might be typing the letter `I` in a Word Document and suddenly it will switch to `edin` without wanting to.

I am not sure what is going on anymore -- I am pretty convinced I do not understand the full logic of your binding system, or missing on something crucial. But right now, I just cannot use it.

Again, sorry for the trouble... would you consider doing a quick Share Screen session to work on this? Or provide me with a full json or anything else you think could help?any help of way of restoring the bindings would be appreciated...

**Comment by pit-ray** [comment]
## About previous my reply
Sorry about that. To avoid long replies, I left out unnecessary parts and included a Before-After json example. BTW Before-After is written in separate code sections, so it does not mean that you can put it in the same array of json. In other words, what I wanted to say in my previous reply is as follows.

**Before [1]**
```json
    {
        "name": "change_to_normal",
        "guin": ["<Esc-Right>"],
        "guii": ["<guin>"],
        "guiv": ["<guin>"],
        "edin": ["<guin>"],
        "edii": ["<guin>"],
        "ediv": ["<guin>"],
        "edivl": ["<guin>"],
        "cmd": [],
        "mycwn": ["<guin>"],
        "mycwi": [],
        "en": "GUI Normal Mode",
        "ja": "GUI ノーマルモード"
    },
```

**Before [2]**
```json
    {
        "name": "change_to_edi_normal",
        "guin": ["I","gI"],
        "guii": [],
        "guiv": [],
        "edin": ["<Esc-Left>"],
        "edii": ["<edin>"],
        "ediv": ["<edin>"],
        "edivl": ["<edin>"],
        "cmd": [],
        "mycwn": [],
        "mycwi": [],
        "en": "Normal Mode (Vim Emulation: <Esc>)",
        "ja": "ノーマルモード (Vim エミュレーション: <Esc>)"
    },
```

**After [1]**
```json
    {
        "name": "change_to_normal",
        "guin": ["<Esc-Left>"],
        "guii": ["<guin>"],
        "guiv": ["<guin>"],
        "edin": ["<guin>"],
        "edii": ["<guin>"],
        "ediv": ["<guin>"],
        "edivl": ["<guin>"],
        "cmd": [],
        "mycwn": ["<guin>"],
        "mycwi": [],
        "en": "GUI Normal Mode",
        "ja": "GUI ノーマルモード"
    },
```

**After [2]**
```json
    {
        "name": "change_to_edi_normal",
        "guin": ["I","gI"],
        "guii": [],
        "guiv": [],
        "edin": ["<Esc-Right>"],
        "edii": ["<edin>"],
        "ediv": ["<edin>"],
        "edivl": ["<edin>"],
        "cmd": [],
        "mycwn": [],
        "mycwi": [],
        "en": "Normal Mode (Vim Emulation: <Esc>)",
        "ja": "ノーマルモード (Vim エミュレーション: <Esc>)"
    },
```

## About json syntax
Example:

```json
    {
        "name": "change_to_normal",
        "guin": ["<Esc-Left>"],           <=====(1)
        "guii": ["binding1"],
        "guiv": ["binding2"],
        "edin": ["binding3"],
        "edii": ["<Esc-Left>"],           <=====(2)
        "ediv": ["binding4"],
        "edivl": ["binding5"],
        "cmd": [],
        "mycwn": ["<guin>"],
        "mycwi": [],
        "en": "GUI Normal Mode",
        "ja": "GUI ノーマルモード"
    },
```

This syntax is the same as the following like `.vimrc` As an example, lines **(1)** and **(2)** are shown below.
```vim
nnoremap <Esc-Left> change_to_normal  " (1)
inoremap <Esc-Left> change_to_normal  " (2)
```
If you are currently in `guin` and press `<Esc-Left>`, the function `change_to_normal` will be called. `change_to_normal` is **a function** that changes the current mode to `guin`.

This means that each function has its array of modes, and is called with the binding corresponding to the current mode. It will not be called in the case of an empty json array. A diagram of this would look like this.

![mode_json](https://user-images.githubusercontent.com/42631247/119504158-ad05ee80-bda6-11eb-9541-a22e546b47fa.jpg)

As mentioned <a href="https://pit-ray.github.io/win-vind/how_to_use/#key-config">here</a>, notations such as `<guin>` and `<guii>` are just copy representations in a json file. In other words, the following **(A)** and **(B)** mean the same thing.

**(A)**
```json
    {
        "name": "change_to_normal",
        "guin": ["<Esc-Left>"],
        "guii": ["<guin>"],
        "guiv": ["<guin>"],
        "edin": ["<guin>"],
        "edii": ["<guin>"],
        "ediv": ["<guin>"],
        "edivl": ["<guin>"],
        "cmd": [],
        "mycwn": ["<guin>"],
        "mycwi": [],
        "en": "GUI Normal Mode",
        "ja": "GUI ノーマルモード"
    },
```

**(B)**
```json
    {
        "name": "change_to_normal",
        "guin": ["<Esc-Left>"],
        "guii": ["<Esc-Left>"],
        "guiv": ["<Esc-Left>"],
        "edin": ["<Esc-Left>"],
        "edii": ["<Esc-Left>"],
        "ediv": ["<Esc-Left>"],
        "edivl": ["<Esc-Left>"],
        "cmd": [],
        "mycwn": ["<Esc-Left>"],
        "mycwi": [],
        "en": "GUI Normal Mode",
        "ja": "GUI ノーマルモード"
    },
```

Incidentally, the json section that you showed does recursive copying. Since there is **NO regularity** in the order of copying, it is undefined whether bindings are assigned to `edii`, `ediv`, or `edivl`.

Thus, `<edin>` and `<guin>` are not commands to change the current mode, but only to copy bindings in json files. And, **keys** in json (e.g. `"guin":`, `"edin":` ) are current mode and **values** (e.g. `["<Esc-Left>"]`) are bindings in each mode.

If you have any questions, please let me know.
Thanks.

**Comment by gilbh** [comment]
Hello and sorry for not responding. My family and I are at a summer camp and I am using my laptop here, with a different keyboard (I use Kinesis on my desktop). Please allow me one more month to get back to business and try the elaborate response above.

Thanks!!

**Comment by pit-ray** [comment]
Today, we released a new version v4, so I closed it to avoid causing some confusion. The above details are for v3 and partially incompatible. Sorry for not contacting you.

The new settings method or mode layers in v4 are thanks to your enthusiastic contributions.
Thanks.

**Comment by gilbh** [comment]
This is fantastic. Again, once I am back on my desktop I'll check the new version and bindings! By making these changes and upgrades, you are making this a very worthwhile project.
